// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var circle, enter, svg, vis;
    vis = d3.select("#graph");
    svg = vis.append("svg");
    svg.attr("width", 300).attr("height", 300);
    circle = svg.selectAll("circle").data([32, 57, 112, 193]);
    enter = circle.enter().append("circle");
    enter.attr("cy", function(d) {
      return d;
    });
    enter.attr("cx", function(d) {
      return d;
    });
    return enter.attr("r", function(d) {
      return Math.sqrt(d);
    });
  };

}).call(this);
