// Generated by CoffeeScript 1.7.1
(function() {
  var makeRange, x;

  makeRange = function(limit) {
    var _i, _results;
    return (function() {
      _results = [];
      for (var _i = 1; 1 <= limit ? _i <= limit : _i >= limit; 1 <= limit ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
  };

  x = makeRange(20);

}).call(this);
